### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by chandankr01** [tangrams/landgrab#4]
python landgrab.py 245707150 20
Downloading http://www.openstreetmap.org/api/0.6/relation/245707150/full
404 Client Error: Not Found for url: http://www.openstreetmap.org/api/0.6/relation/245707150/full
Downloading http://www.openstreetmap.org/api/0.6/way/245707150/full
Processing:
tiles:[{'y': 347045.0, 'x': 544221.0, 'z': 20}, {'y': 347044.0, 'x': 544221.0, 'z': 20}]

Downloading 41 tiles at zoom level 9
0%Traceback (most recent call last):
  File "landgrab.py", line 256, in <module>
    getTiles(points,z)
  File "landgrab.py", line 222, in getTiles
    j = json.loads(r.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by meetar** [comment]
Hi @chandankr01 – the datasource was out of date, so I updated it with https://github.com/tangrams/landgrab/commit/217699e4730a1bdb7c9e03bfd9c2c0c31950eb7c – however the new datasource only allows zoom levels up to 16, so you won't be able to download them at 20 as you're attempting.

(Were you mixing error messages there? You shouldn't have seen "Downloading 41 tiles at zoom level 9" if you were downloading at zoom 20...)

Hope this is helpful!

**Comment by chandankr01** [comment]
Thank you so much !
